# This rule is not used by the project kroc itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.pwlctk.ovh.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kroc
    app.kubernetes.io/managed-by: kustomize
  name: kroc-admin-role
rules:
- apiGroups:
  - apps.pwlctk.ovh
  resources:
  - krocs
  verbs:
  - '*'
- apiGroups:
  - apps.pwlctk.ovh
  resources:
  - krocs/status
  verbs:
  - get
